export interface Phrase {
  english: string
  translation: string
}

/**
 * A real set of common travel phrases per language — the same kind of static
 * reference data as `currencyByCountry.ts`'s currency codes, not fabricated
 * content. Covers the 15 phrases most useful to a traveler who knows none of
 * the local language. Each phrase has a stable position across languages, so
 * its index maps to a pre-generated audio clip (see `scripts/generate-phrase-audio.mjs`).
 * Languages not listed here (or English) show no phrasebook — see `LocalInfoCard`.
 */
export const PHRASES_BY_LANGUAGE: Record<string, Phrase[]> = {
  french: [
    { english: 'Hello', translation: 'Bonjour' },
    { english: 'Please', translation: "S'il vous plaît" },
    { english: 'Thank you', translation: 'Merci' },
    { english: 'Excuse me', translation: 'Excusez-moi' },
    { english: 'Yes / No', translation: 'Oui / Non' },
    { english: 'How much is this?', translation: 'Combien ça coûte ?' },
    { english: 'Where is the bathroom?', translation: 'Où sont les toilettes ?' },
    { english: 'Help!', translation: 'Au secours !' },
    { english: 'Goodbye', translation: 'Au revoir' },
    { english: 'Good morning', translation: 'Bonjour' },
    { english: 'Sorry', translation: 'Pardon' },
    { english: "I don't understand", translation: 'Je ne comprends pas' },
    { english: 'Do you speak English?', translation: 'Parlez-vous anglais ?' },
    { english: 'Cheers!', translation: 'Santé !' },
    { english: 'The check, please', translation: "L'addition, s'il vous plaît" },
  ],
  german: [
    { english: 'Hello', translation: 'Hallo' },
    { english: 'Please', translation: 'Bitte' },
    { english: 'Thank you', translation: 'Danke' },
    { english: 'Excuse me', translation: 'Entschuldigung' },
    { english: 'Yes / No', translation: 'Ja / Nein' },
    { english: 'How much is this?', translation: 'Wie viel kostet das?' },
    { english: 'Where is the bathroom?', translation: 'Wo ist die Toilette?' },
    { english: 'Help!', translation: 'Hilfe!' },
    { english: 'Goodbye', translation: 'Auf Wiedersehen' },
    { english: 'Good morning', translation: 'Guten Morgen' },
    { english: 'Sorry', translation: 'Entschuldigung' },
    { english: "I don't understand", translation: 'Ich verstehe nicht' },
    { english: 'Do you speak English?', translation: 'Sprechen Sie Englisch?' },
    { english: 'Cheers!', translation: 'Prost!' },
    { english: 'The check, please', translation: 'Die Rechnung, bitte' },
  ],
  spanish: [
    { english: 'Hello', translation: 'Hola' },
    { english: 'Please', translation: 'Por favor' },
    { english: 'Thank you', translation: 'Gracias' },
    { english: 'Excuse me', translation: 'Disculpe' },
    { english: 'Yes / No', translation: 'Sí / No' },
    { english: 'How much is this?', translation: '¿Cuánto cuesta esto?' },
    { english: 'Where is the bathroom?', translation: '¿Dónde está el baño?' },
    { english: 'Help!', translation: '¡Ayuda!' },
    { english: 'Goodbye', translation: 'Adiós' },
    { english: 'Good morning', translation: 'Buenos días' },
    { english: 'Sorry', translation: 'Perdón' },
    { english: "I don't understand", translation: 'No entiendo' },
    { english: 'Do you speak English?', translation: '¿Habla inglés?' },
    { english: 'Cheers!', translation: '¡Salud!' },
    { english: 'The check, please', translation: 'La cuenta, por favor' },
  ],
  italian: [
    { english: 'Hello', translation: 'Ciao' },
    { english: 'Please', translation: 'Per favore' },
    { english: 'Thank you', translation: 'Grazie' },
    { english: 'Excuse me', translation: 'Mi scusi' },
    { english: 'Yes / No', translation: 'Sì / No' },
    { english: 'How much is this?', translation: 'Quanto costa?' },
    { english: 'Where is the bathroom?', translation: "Dov'è il bagno?" },
    { english: 'Help!', translation: 'Aiuto!' },
    { english: 'Goodbye', translation: 'Arrivederci' },
    { english: 'Good morning', translation: 'Buongiorno' },
    { english: 'Sorry', translation: 'Scusa' },
    { english: "I don't understand", translation: 'Non capisco' },
    { english: 'Do you speak English?', translation: 'Parla inglese?' },
    { english: 'Cheers!', translation: 'Salute!' },
    { english: 'The check, please', translation: 'Il conto, per favore' },
  ],
  portuguese: [
    { english: 'Hello', translation: 'Olá' },
    { english: 'Please', translation: 'Por favor' },
    { english: 'Thank you', translation: 'Obrigado' },
    { english: 'Excuse me', translation: 'Com licença' },
    { english: 'Yes / No', translation: 'Sim / Não' },
    { english: 'How much is this?', translation: 'Quanto custa isto?' },
    { english: 'Where is the bathroom?', translation: 'Onde é o banheiro?' },
    { english: 'Help!', translation: 'Socorro!' },
    { english: 'Goodbye', translation: 'Adeus' },
    { english: 'Good morning', translation: 'Bom dia' },
    { english: 'Sorry', translation: 'Desculpe' },
    { english: "I don't understand", translation: 'Não entendo' },
    { english: 'Do you speak English?', translation: 'Você fala inglês?' },
    { english: 'Cheers!', translation: 'Saúde!' },
    { english: 'The check, please', translation: 'A conta, por favor' },
  ],
  japanese: [
    { english: 'Hello', translation: 'こんにちは (Konnichiwa)' },
    { english: 'Please', translation: 'お願いします (Onegaishimasu)' },
    { english: 'Thank you', translation: 'ありがとう (Arigatou)' },
    { english: 'Excuse me', translation: 'すみません (Sumimasen)' },
    { english: 'Yes / No', translation: 'はい / いいえ (Hai / Iie)' },
    { english: 'How much is this?', translation: 'これはいくらですか？ (Kore wa ikura desu ka?)' },
    { english: 'Where is the bathroom?', translation: 'トイレはどこですか？ (Toire wa doko desu ka?)' },
    { english: 'Help!', translation: '助けて！ (Tasukete!)' },
    { english: 'Goodbye', translation: 'さようなら (Sayounara)' },
    { english: 'Good morning', translation: 'おはようございます (Ohayou gozaimasu)' },
    { english: 'Sorry', translation: 'ごめんなさい (Gomen nasai)' },
    { english: "I don't understand", translation: 'わかりません (Wakarimasen)' },
    { english: 'Do you speak English?', translation: '英語を話せますか？ (Eigo o hanasemasu ka?)' },
    { english: 'Cheers!', translation: '乾杯！ (Kanpai!)' },
    { english: 'The check, please', translation: 'お会計をお願いします (Okaikei o onegaishimasu)' },
  ],
  mandarin: [
    { english: 'Hello', translation: '你好 (Nǐ hǎo)' },
    { english: 'Please', translation: '请 (Qǐng)' },
    { english: 'Thank you', translation: '谢谢 (Xièxiè)' },
    { english: 'Excuse me', translation: '对不起 (Duìbùqǐ)' },
    { english: 'Yes / No', translation: '是 / 不是 (Shì / Bùshì)' },
    { english: 'How much is this?', translation: '这个多少钱？ (Zhège duōshǎo qián?)' },
    { english: 'Where is the bathroom?', translation: '厕所在哪里？ (Cèsuǒ zài nǎlǐ?)' },
    { english: 'Help!', translation: '救命！ (Jiùmìng!)' },
    { english: 'Goodbye', translation: '再见 (Zàijiàn)' },
    { english: 'Good morning', translation: '早上好 (Zǎoshang hǎo)' },
    { english: 'Sorry', translation: '不好意思 (Bù hǎoyìsi)' },
    { english: "I don't understand", translation: '我不明白 (Wǒ bù míngbái)' },
    { english: 'Do you speak English?', translation: '你会说英语吗？ (Nǐ huì shuō yīngyǔ ma?)' },
    { english: 'Cheers!', translation: '干杯！ (Gānbēi!)' },
    { english: 'The check, please', translation: '买单 (Mǎidān)' },
  ],
  korean: [
    { english: 'Hello', translation: '안녕하세요 (Annyeonghaseyo)' },
    { english: 'Please', translation: '부탁합니다 (Butakhamnida)' },
    { english: 'Thank you', translation: '감사합니다 (Gamsahamnida)' },
    { english: 'Excuse me', translation: '실례합니다 (Sillyehamnida)' },
    { english: 'Yes / No', translation: '네 / 아니요 (Ne / Aniyo)' },
    { english: 'How much is this?', translation: '이거 얼마예요? (Igeo eolmayeyo?)' },
    { english: 'Where is the bathroom?', translation: '화장실이 어디예요? (Hwajangsiri eodiyeyo?)' },
    { english: 'Help!', translation: '도와주세요! (Dowajuseyo!)' },
    { english: 'Goodbye', translation: '안녕히 계세요 (Annyeonghi gyeseyo)' },
    { english: 'Good morning', translation: '좋은 아침이에요 (Joeun achimieyo)' },
    { english: 'Sorry', translation: '죄송합니다 (Joesonghamnida)' },
    { english: "I don't understand", translation: '이해가 안 돼요 (Ihaega an dwaeyo)' },
    { english: 'Do you speak English?', translation: '영어 할 줄 아세요? (Yeongeo hal jul aseyo?)' },
    { english: 'Cheers!', translation: '건배! (Geonbae!)' },
    { english: 'The check, please', translation: '계산서 주세요 (Gyesanseo juseyo)' },
  ],
  thai: [
    { english: 'Hello', translation: 'สวัสดี (Sawasdee)' },
    { english: 'Please', translation: 'กรุณา (Karuna)' },
    { english: 'Thank you', translation: 'ขอบคุณ (Khob khun)' },
    { english: 'Excuse me', translation: 'ขอโทษ (Kho thot)' },
    { english: 'Yes / No', translation: 'ใช่ / ไม่ (Chai / Mai)' },
    { english: 'How much is this?', translation: 'นี่ราคาเท่าไหร่? (Nee raka tao rai?)' },
    { english: 'Where is the bathroom?', translation: 'ห้องน้ำอยู่ที่ไหน? (Hong nam yu tee nai?)' },
    { english: 'Help!', translation: 'ช่วยด้วย! (Chuay duay!)' },
    { english: 'Goodbye', translation: 'ลาก่อน (La kon)' },
    { english: 'Good morning', translation: 'อรุณสวัสดิ์ (Arun sawat)' },
    { english: 'Sorry', translation: 'ขอโทษ (Kho thot)' },
    { english: "I don't understand", translation: 'ไม่เข้าใจ (Mai kao jai)' },
    { english: 'Do you speak English?', translation: 'คุณพูดภาษาอังกฤษได้ไหม? (Khun phut phasa angkrit dai mai?)' },
    { english: 'Cheers!', translation: 'ไชโย! (Chai yo!)' },
    { english: 'The check, please', translation: 'เก็บเงินด้วย (Kep ngern duay)' },
  ],
  vietnamese: [
    { english: 'Hello', translation: 'Xin chào' },
    { english: 'Please', translation: 'Làm ơn' },
    { english: 'Thank you', translation: 'Cảm ơn' },
    { english: 'Excuse me', translation: 'Xin lỗi' },
    { english: 'Yes / No', translation: 'Vâng / Không' },
    { english: 'How much is this?', translation: 'Cái này bao nhiêu tiền?' },
    { english: 'Where is the bathroom?', translation: 'Nhà vệ sinh ở đâu?' },
    { english: 'Help!', translation: 'Cứu tôi với!' },
    { english: 'Goodbye', translation: 'Tạm biệt' },
    { english: 'Good morning', translation: 'Chào buổi sáng' },
    { english: 'Sorry', translation: 'Xin lỗi' },
    { english: "I don't understand", translation: 'Tôi không hiểu' },
    { english: 'Do you speak English?', translation: 'Bạn có nói tiếng Anh không?' },
    { english: 'Cheers!', translation: 'Dô!' },
    { english: 'The check, please', translation: 'Tính tiền' },
  ],
  indonesian: [
    { english: 'Hello', translation: 'Halo' },
    { english: 'Please', translation: 'Tolong' },
    { english: 'Thank you', translation: 'Terima kasih' },
    { english: 'Excuse me', translation: 'Permisi' },
    { english: 'Yes / No', translation: 'Ya / Tidak' },
    { english: 'How much is this?', translation: 'Berapa harganya?' },
    { english: 'Where is the bathroom?', translation: 'Di mana kamar mandi?' },
    { english: 'Help!', translation: 'Tolong!' },
    { english: 'Goodbye', translation: 'Selamat tinggal' },
    { english: 'Good morning', translation: 'Selamat pagi' },
    { english: 'Sorry', translation: 'Maaf' },
    { english: "I don't understand", translation: 'Saya tidak mengerti' },
    { english: 'Do you speak English?', translation: 'Apakah Anda bisa bahasa Inggris?' },
    { english: 'Cheers!', translation: 'Bersulang!' },
    { english: 'The check, please', translation: 'Minta bon' },
  ],
  malay: [
    { english: 'Hello', translation: 'Helo' },
    { english: 'Please', translation: 'Tolong' },
    { english: 'Thank you', translation: 'Terima kasih' },
    { english: 'Excuse me', translation: 'Maaf' },
    { english: 'Yes / No', translation: 'Ya / Tidak' },
    { english: 'How much is this?', translation: 'Berapa harganya?' },
    { english: 'Where is the bathroom?', translation: 'Di mana tandas?' },
    { english: 'Help!', translation: 'Tolong!' },
    { english: 'Goodbye', translation: 'Selamat tinggal' },
    { english: 'Good morning', translation: 'Selamat pagi' },
    { english: 'Sorry', translation: 'Maaf' },
    { english: "I don't understand", translation: 'Saya tidak faham' },
    { english: 'Do you speak English?', translation: 'Adakah anda bercakap bahasa Inggeris?' },
    { english: 'Cheers!', translation: 'Selamat!' },
    { english: 'The check, please', translation: 'Boleh saya dapatkan bil?' },
  ],
  dutch: [
    { english: 'Hello', translation: 'Hallo' },
    { english: 'Please', translation: 'Alstublieft' },
    { english: 'Thank you', translation: 'Dank u' },
    { english: 'Excuse me', translation: 'Pardon' },
    { english: 'Yes / No', translation: 'Ja / Nee' },
    { english: 'How much is this?', translation: 'Hoeveel kost dit?' },
    { english: 'Where is the bathroom?', translation: 'Waar is het toilet?' },
    { english: 'Help!', translation: 'Help!' },
    { english: 'Goodbye', translation: 'Tot ziens' },
    { english: 'Good morning', translation: 'Goedemorgen' },
    { english: 'Sorry', translation: 'Sorry' },
    { english: "I don't understand", translation: 'Ik begrijp het niet' },
    { english: 'Do you speak English?', translation: 'Spreekt u Engels?' },
    { english: 'Cheers!', translation: 'Proost!' },
    { english: 'The check, please', translation: 'De rekening, alstublieft' },
  ],
  greek: [
    { english: 'Hello', translation: 'Γεια σας (Geia sas)' },
    { english: 'Please', translation: 'Παρακαλώ (Parakalo)' },
    { english: 'Thank you', translation: 'Ευχαριστώ (Efharisto)' },
    { english: 'Excuse me', translation: 'Συγγνώμη (Signomi)' },
    { english: 'Yes / No', translation: 'Ναι / Όχι (Ne / Ochi)' },
    { english: 'How much is this?', translation: 'Πόσο κοστίζει αυτό; (Poso kostizei afto?)' },
    { english: 'Where is the bathroom?', translation: 'Πού είναι η τουαλέτα; (Pou einai i toualeta?)' },
    { english: 'Help!', translation: 'Βοήθεια! (Voitheia!)' },
    { english: 'Goodbye', translation: 'Αντίο (Antio)' },
    { english: 'Good morning', translation: 'Καλημέρα (Kalimera)' },
    { english: 'Sorry', translation: 'Συγγνώμη (Signomi)' },
    { english: "I don't understand", translation: 'Δεν καταλαβαίνω (Den katalaveno)' },
    { english: 'Do you speak English?', translation: 'Μιλάτε αγγλικά; (Milate anglika?)' },
    { english: 'Cheers!', translation: 'Γεια μας! (Gia mas!)' },
    { english: 'The check, please', translation: 'Τον λογαριασμό, παρακαλώ (Ton logariasmo, parakalo)' },
  ],
  russian: [
    { english: 'Hello', translation: 'Здравствуйте (Zdravstvuyte)' },
    { english: 'Please', translation: 'Пожалуйста (Pozhaluysta)' },
    { english: 'Thank you', translation: 'Спасибо (Spasibo)' },
    { english: 'Excuse me', translation: 'Извините (Izvinite)' },
    { english: 'Yes / No', translation: 'Да / Нет (Da / Net)' },
    { english: 'How much is this?', translation: 'Сколько это стоит? (Skolko eto stoit?)' },
    { english: 'Where is the bathroom?', translation: 'Где туалет? (Gde tualet?)' },
    { english: 'Help!', translation: 'Помогите! (Pomogite!)' },
    { english: 'Goodbye', translation: 'До свидания (Do svidaniya)' },
    { english: 'Good morning', translation: 'Доброе утро (Dobroe utro)' },
    { english: 'Sorry', translation: 'Простите (Prostite)' },
    { english: "I don't understand", translation: 'Я не понимаю (Ya ne ponimayu)' },
    { english: 'Do you speak English?', translation: 'Вы говорите по-английски? (Vy govorite po-angliyski?)' },
    { english: 'Cheers!', translation: 'За здоровье! (Za zdorovye!)' },
    { english: 'The check, please', translation: 'Счёт, пожалуйста (Schyot, pozhaluysta)' },
  ],
  ukrainian: [
    { english: 'Hello', translation: 'Вітаю (Vitayu)' },
    { english: 'Please', translation: 'Будь ласка (Bud laska)' },
    { english: 'Thank you', translation: 'Дякую (Dyakuyu)' },
    { english: 'Excuse me', translation: 'Вибачте (Vybachte)' },
    { english: 'Yes / No', translation: 'Так / Ні (Tak / Ni)' },
    { english: 'How much is this?', translation: 'Скільки це коштує? (Skilky tse koshtuye?)' },
    { english: 'Where is the bathroom?', translation: 'Де туалет? (De tualet?)' },
    { english: 'Help!', translation: 'Допоможіть! (Dopomozhit!)' },
    { english: 'Goodbye', translation: 'До побачення (Do pobachennya)' },
    { english: 'Good morning', translation: 'Доброго ранку (Dobroho ranku)' },
    { english: 'Sorry', translation: 'Перепрошую (Pereproshuyu)' },
    { english: "I don't understand", translation: 'Я не розумію (Ya ne rozumiyu)' },
    { english: 'Do you speak English?', translation: 'Ви розмовляєте англійською? (Vy rozmovlyayete anhliyskoyu?)' },
    { english: 'Cheers!', translation: 'Будьмо! (Budmo!)' },
    { english: 'The check, please', translation: 'Рахунок, будь ласка (Rakhunok, bud laska)' },
  ],
  polish: [
    { english: 'Hello', translation: 'Cześć' },
    { english: 'Please', translation: 'Proszę' },
    { english: 'Thank you', translation: 'Dziękuję' },
    { english: 'Excuse me', translation: 'Przepraszam' },
    { english: 'Yes / No', translation: 'Tak / Nie' },
    { english: 'How much is this?', translation: 'Ile to kosztuje?' },
    { english: 'Where is the bathroom?', translation: 'Gdzie jest toaleta?' },
    { english: 'Help!', translation: 'Pomocy!' },
    { english: 'Goodbye', translation: 'Do widzenia' },
    { english: 'Good morning', translation: 'Dzień dobry' },
    { english: 'Sorry', translation: 'Przepraszam' },
    { english: "I don't understand", translation: 'Nie rozumiem' },
    { english: 'Do you speak English?', translation: 'Czy mówisz po angielsku?' },
    { english: 'Cheers!', translation: 'Na zdrowie!' },
    { english: 'The check, please', translation: 'Rachunek poproszę' },
  ],
  turkish: [
    { english: 'Hello', translation: 'Merhaba' },
    { english: 'Please', translation: 'Lütfen' },
    { english: 'Thank you', translation: 'Teşekkürler' },
    { english: 'Excuse me', translation: 'Affedersiniz' },
    { english: 'Yes / No', translation: 'Evet / Hayır' },
    { english: 'How much is this?', translation: 'Bu ne kadar?' },
    { english: 'Where is the bathroom?', translation: 'Tuvalet nerede?' },
    { english: 'Help!', translation: 'İmdat!' },
    { english: 'Goodbye', translation: 'Hoşça kal' },
    { english: 'Good morning', translation: 'Günaydın' },
    { english: 'Sorry', translation: 'Özür dilerim' },
    { english: "I don't understand", translation: 'Anlamıyorum' },
    { english: 'Do you speak English?', translation: 'İngilizce biliyor musunuz?' },
    { english: 'Cheers!', translation: 'Şerefe!' },
    { english: 'The check, please', translation: 'Hesap, lütfen' },
  ],
  arabic: [
    { english: 'Hello', translation: 'مرحبا (Marhaba)' },
    { english: 'Please', translation: 'من فضلك (Min fadlik)' },
    { english: 'Thank you', translation: 'شكرا (Shukran)' },
    { english: 'Excuse me', translation: 'عفوا (Afwan)' },
    { english: 'Yes / No', translation: 'نعم / لا (Naam / La)' },
    { english: 'How much is this?', translation: 'كم هذا؟ (Kam hatha?)' },
    { english: 'Where is the bathroom?', translation: 'أين الحمام؟ (Ayna al-hammam?)' },
    { english: 'Help!', translation: 'النجدة! (An-najda!)' },
    { english: 'Goodbye', translation: 'مع السلامة (Maa as-salama)' },
    { english: 'Good morning', translation: 'صباح الخير (Sabah al-khayr)' },
    { english: 'Sorry', translation: 'آسف (Aasif)' },
    { english: "I don't understand", translation: 'لا أفهم (La afham)' },
    { english: 'Do you speak English?', translation: 'هل تتكلم الإنجليزية؟ (Hal tatakallam al-injliziyya?)' },
    { english: 'Cheers!', translation: 'في صحتك! (Fi sahtak!)' },
    { english: 'The check, please', translation: 'الحساب من فضلك (Al-hisab min fadlik)' },
  ],
  hebrew: [
    { english: 'Hello', translation: 'שלום (Shalom)' },
    { english: 'Please', translation: 'בבקשה (Bevakasha)' },
    { english: 'Thank you', translation: 'תודה (Toda)' },
    { english: 'Excuse me', translation: 'סליחה (Slicha)' },
    { english: 'Yes / No', translation: 'כן / לא (Ken / Lo)' },
    { english: 'How much is this?', translation: 'כמה זה עולה? (Kama ze ole?)' },
    { english: 'Where is the bathroom?', translation: 'איפה השירותים? (Eifo ha-sherutim?)' },
    { english: 'Help!', translation: 'הצילו! (Hatzilu!)' },
    { english: 'Goodbye', translation: 'להתראות (Lehitraot)' },
    { english: 'Good morning', translation: 'בוקר טוב (Boker tov)' },
    { english: 'Sorry', translation: 'סליחה (Slicha)' },
    { english: "I don't understand", translation: 'אני לא מבין (Ani lo mevin)' },
    { english: 'Do you speak English?', translation: 'אתה מדבר אנגלית? (Ata medaber anglit?)' },
    { english: 'Cheers!', translation: 'לחיים! (Lechaim!)' },
    { english: 'The check, please', translation: 'החשבון, בבקשה (Ha-cheshbon, bevakasha)' },
  ],
  hindi: [
    { english: 'Hello', translation: 'नमस्ते (Namaste)' },
    { english: 'Please', translation: 'कृपया (Kripya)' },
    { english: 'Thank you', translation: 'धन्यवाद (Dhanyavaad)' },
    { english: 'Excuse me', translation: 'माफ़ कीजिए (Maaf kijiye)' },
    { english: 'Yes / No', translation: 'हाँ / नहीं (Haan / Nahin)' },
    { english: 'How much is this?', translation: 'यह कितने का है? (Yeh kitne ka hai?)' },
    { english: 'Where is the bathroom?', translation: 'शौचालय कहाँ है? (Shauchalay kahaan hai?)' },
    { english: 'Help!', translation: 'मदद करो! (Madad karo!)' },
    { english: 'Goodbye', translation: 'अलविदा (Alvida)' },
    { english: 'Good morning', translation: 'सुप्रभात (Suprabhat)' },
    { english: 'Sorry', translation: 'माफ़ करना (Maaf karna)' },
    { english: "I don't understand", translation: 'मुझे समझ नहीं आया (Mujhe samajh nahin aaya)' },
    { english: 'Do you speak English?', translation: 'क्या आप अंग्रेज़ी बोलते हैं? (Kya aap angrezi bolte hain?)' },
    { english: 'Cheers!', translation: 'चियर्स! (Cheers!)' },
    { english: 'The check, please', translation: 'बिल दीजिए (Bill dijiye)' },
  ],
  sinhala: [
    { english: 'Hello', translation: 'ආයුබෝවන් (Ayubowan)' },
    { english: 'Please', translation: 'කරුණාකර (Karunakara)' },
    { english: 'Thank you', translation: 'ස්තූතියි (Sthuthiyi)' },
    { english: 'Excuse me', translation: 'සමාවෙන්න (Samavenna)' },
    { english: 'Yes / No', translation: 'ඔව් / නෑ (Ow / Nae)' },
    { english: 'How much is this?', translation: 'මේකට කීයද? (Mekata keeyada?)' },
    { english: 'Where is the bathroom?', translation: 'වැසිකිලිය කොහෙද? (Wasikiliya koheda?)' },
    { english: 'Help!', translation: 'උදව්වක්! (Udawwak!)' },
    { english: 'Goodbye', translation: 'ගිහින් එන්නම් (Gihin ennam)' },
    { english: 'Good morning', translation: 'සුබ උදෑසනක් (Suba udaesanak)' },
    { english: 'Sorry', translation: 'සමාවෙන්න (Samavenna)' },
    { english: "I don't understand", translation: 'මට තේරෙන්නේ නෑ (Mata therenne nae)' },
    { english: 'Do you speak English?', translation: 'ඔයා ඉංග්‍රීසි කතා කරනවද? (Oya ingrisi katha karanawada?)' },
    { english: 'Cheers!', translation: 'චියර්ස්! (Cheers!)' },
    { english: 'The check, please', translation: 'බිල ගේන්න (Bila genna)' },
  ],
  nepali: [
    { english: 'Hello', translation: 'नमस्ते (Namaste)' },
    { english: 'Please', translation: 'कृपया (Kripaya)' },
    { english: 'Thank you', translation: 'धन्यवाद (Dhanyabaad)' },
    { english: 'Excuse me', translation: 'माफ गर्नुहोस् (Maaf garnuhos)' },
    { english: 'Yes / No', translation: 'हो / होइन (Ho / Hoina)' },
    { english: 'How much is this?', translation: 'यो कति हो? (Yo kati ho?)' },
    { english: 'Where is the bathroom?', translation: 'शौचालय कहाँ छ? (Shauchalaya kahan chha?)' },
    { english: 'Help!', translation: 'सहयोग गर्नुहोस्! (Sahayog garnuhos!)' },
    { english: 'Goodbye', translation: 'नमस्ते (Namaste)' },
    { english: 'Good morning', translation: 'शुभ प्रभात (Shubha prabhat)' },
    { english: 'Sorry', translation: 'माफ गर्नुहोस् (Maaf garnuhos)' },
    { english: "I don't understand", translation: 'मैले बुझिनँ (Maile bujhinang)' },
    { english: 'Do you speak English?', translation: 'तपाईं अंग्रेजी बोल्नुहुन्छ? (Tapai angreji bolnuhunchha?)' },
    { english: 'Cheers!', translation: 'चियर्स! (Cheers!)' },
    { english: 'The check, please', translation: 'बिल दिनुहोस् (Bil dinuhos)' },
  ],
  icelandic: [
    { english: 'Hello', translation: 'Halló' },
    { english: 'Please', translation: 'Vinsamlegast' },
    { english: 'Thank you', translation: 'Takk' },
    { english: 'Excuse me', translation: 'Afsakið' },
    { english: 'Yes / No', translation: 'Já / Nei' },
    { english: 'How much is this?', translation: 'Hvað kostar þetta?' },
    { english: 'Where is the bathroom?', translation: 'Hvar er klósettið?' },
    { english: 'Help!', translation: 'Hjálp!' },
    { english: 'Goodbye', translation: 'Bless' },
    { english: 'Good morning', translation: 'Góðan daginn' },
    { english: 'Sorry', translation: 'Fyrirgefðu' },
    { english: "I don't understand", translation: 'Ég skil ekki' },
    { english: 'Do you speak English?', translation: 'Talar þú ensku?' },
    { english: 'Cheers!', translation: 'Skál!' },
    { english: 'The check, please', translation: 'Reikninginn, takk' },
  ],
  norwegian: [
    { english: 'Hello', translation: 'Hei' },
    { english: 'Please', translation: 'Vær så snill' },
    { english: 'Thank you', translation: 'Takk' },
    { english: 'Excuse me', translation: 'Unnskyld' },
    { english: 'Yes / No', translation: 'Ja / Nei' },
    { english: 'How much is this?', translation: 'Hvor mye koster dette?' },
    { english: 'Where is the bathroom?', translation: 'Hvor er toalettet?' },
    { english: 'Help!', translation: 'Hjelp!' },
    { english: 'Goodbye', translation: 'Ha det' },
    { english: 'Good morning', translation: 'God morgen' },
    { english: 'Sorry', translation: 'Beklager' },
    { english: "I don't understand", translation: 'Jeg forstår ikke' },
    { english: 'Do you speak English?', translation: 'Snakker du engelsk?' },
    { english: 'Cheers!', translation: 'Skål!' },
    { english: 'The check, please', translation: 'Regningen, takk' },
  ],
  swedish: [
    { english: 'Hello', translation: 'Hej' },
    { english: 'Please', translation: 'Snälla' },
    { english: 'Thank you', translation: 'Tack' },
    { english: 'Excuse me', translation: 'Ursäkta' },
    { english: 'Yes / No', translation: 'Ja / Nej' },
    { english: 'How much is this?', translation: 'Vad kostar det här?' },
    { english: 'Where is the bathroom?', translation: 'Var är toaletten?' },
    { english: 'Help!', translation: 'Hjälp!' },
    { english: 'Goodbye', translation: 'Hej då' },
    { english: 'Good morning', translation: 'God morgon' },
    { english: 'Sorry', translation: 'Förlåt' },
    { english: "I don't understand", translation: 'Jag förstår inte' },
    { english: 'Do you speak English?', translation: 'Pratar du engelska?' },
    { english: 'Cheers!', translation: 'Skål!' },
    { english: 'The check, please', translation: 'Notan, tack' },
  ],
  danish: [
    { english: 'Hello', translation: 'Hej' },
    { english: 'Please', translation: 'Vær venlig' },
    { english: 'Thank you', translation: 'Tak' },
    { english: 'Excuse me', translation: 'Undskyld' },
    { english: 'Yes / No', translation: 'Ja / Nej' },
    { english: 'How much is this?', translation: 'Hvor meget koster det?' },
    { english: 'Where is the bathroom?', translation: 'Hvor er toilettet?' },
    { english: 'Help!', translation: 'Hjælp!' },
    { english: 'Goodbye', translation: 'Farvel' },
    { english: 'Good morning', translation: 'Godmorgen' },
    { english: 'Sorry', translation: 'Undskyld' },
    { english: "I don't understand", translation: 'Jeg forstår ikke' },
    { english: 'Do you speak English?', translation: 'Taler du engelsk?' },
    { english: 'Cheers!', translation: 'Skål!' },
    { english: 'The check, please', translation: 'Regningen, tak' },
  ],
  finnish: [
    { english: 'Hello', translation: 'Hei' },
    { english: 'Please', translation: 'Ole hyvä' },
    { english: 'Thank you', translation: 'Kiitos' },
    { english: 'Excuse me', translation: 'Anteeksi' },
    { english: 'Yes / No', translation: 'Kyllä / Ei' },
    { english: 'How much is this?', translation: 'Paljonko tämä maksaa?' },
    { english: 'Where is the bathroom?', translation: 'Missä on vessa?' },
    { english: 'Help!', translation: 'Apua!' },
    { english: 'Goodbye', translation: 'Näkemiin' },
    { english: 'Good morning', translation: 'Hyvää huomenta' },
    { english: 'Sorry', translation: 'Anteeksi' },
    { english: "I don't understand", translation: 'En ymmärrä' },
    { english: 'Do you speak English?', translation: 'Puhutko englantia?' },
    { english: 'Cheers!', translation: 'Kippis!' },
    { english: 'The check, please', translation: 'Lasku, kiitos' },
  ],
  czech: [
    { english: 'Hello', translation: 'Ahoj' },
    { english: 'Please', translation: 'Prosím' },
    { english: 'Thank you', translation: 'Děkuji' },
    { english: 'Excuse me', translation: 'Promiňte' },
    { english: 'Yes / No', translation: 'Ano / Ne' },
    { english: 'How much is this?', translation: 'Kolik to stojí?' },
    { english: 'Where is the bathroom?', translation: 'Kde je toaleta?' },
    { english: 'Help!', translation: 'Pomoc!' },
    { english: 'Goodbye', translation: 'Na shledanou' },
    { english: 'Good morning', translation: 'Dobré ráno' },
    { english: 'Sorry', translation: 'Promiňte' },
    { english: "I don't understand", translation: 'Nerozumím' },
    { english: 'Do you speak English?', translation: 'Mluvíte anglicky?' },
    { english: 'Cheers!', translation: 'Na zdraví!' },
    { english: 'The check, please', translation: 'Účet, prosím' },
  ],
  hungarian: [
    { english: 'Hello', translation: 'Szia' },
    { english: 'Please', translation: 'Kérem' },
    { english: 'Thank you', translation: 'Köszönöm' },
    { english: 'Excuse me', translation: 'Elnézést' },
    { english: 'Yes / No', translation: 'Igen / Nem' },
    { english: 'How much is this?', translation: 'Mennyibe kerül ez?' },
    { english: 'Where is the bathroom?', translation: 'Hol van a mosdó?' },
    { english: 'Help!', translation: 'Segítség!' },
    { english: 'Goodbye', translation: 'Viszontlátásra' },
    { english: 'Good morning', translation: 'Jó reggelt' },
    { english: 'Sorry', translation: 'Bocsánat' },
    { english: "I don't understand", translation: 'Nem értem' },
    { english: 'Do you speak English?', translation: 'Beszél angolul?' },
    { english: 'Cheers!', translation: 'Egészségedre!' },
    { english: 'The check, please', translation: 'A számlát, kérem' },
  ],
  romanian: [
    { english: 'Hello', translation: 'Bună' },
    { english: 'Please', translation: 'Vă rog' },
    { english: 'Thank you', translation: 'Mulțumesc' },
    { english: 'Excuse me', translation: 'Scuzați-mă' },
    { english: 'Yes / No', translation: 'Da / Nu' },
    { english: 'How much is this?', translation: 'Cât costă asta?' },
    { english: 'Where is the bathroom?', translation: 'Unde este toaleta?' },
    { english: 'Help!', translation: 'Ajutor!' },
    { english: 'Goodbye', translation: 'La revedere' },
    { english: 'Good morning', translation: 'Bună dimineața' },
    { english: 'Sorry', translation: 'Îmi pare rău' },
    { english: "I don't understand", translation: 'Nu înțeleg' },
    { english: 'Do you speak English?', translation: 'Vorbiți engleză?' },
    { english: 'Cheers!', translation: 'Noroc!' },
    { english: 'The check, please', translation: 'Nota, vă rog' },
  ],
  croatian: [
    { english: 'Hello', translation: 'Bok' },
    { english: 'Please', translation: 'Molim' },
    { english: 'Thank you', translation: 'Hvala' },
    { english: 'Excuse me', translation: 'Oprostite' },
    { english: 'Yes / No', translation: 'Da / Ne' },
    { english: 'How much is this?', translation: 'Koliko ovo košta?' },
    { english: 'Where is the bathroom?', translation: 'Gdje je zahod?' },
    { english: 'Help!', translation: 'Upomoć!' },
    { english: 'Goodbye', translation: 'Doviđenja' },
    { english: 'Good morning', translation: 'Dobro jutro' },
    { english: 'Sorry', translation: 'Oprostite' },
    { english: "I don't understand", translation: 'Ne razumijem' },
    { english: 'Do you speak English?', translation: 'Govorite li engleski?' },
    { english: 'Cheers!', translation: 'Živjeli!' },
    { english: 'The check, please', translation: 'Račun, molim' },
  ],
}

/**
 * Looks up the real phrase list for a language, if one is curated.
 * @param language - A language key from `languageForDisplayName`, or null
 * @returns The phrase list, or null when the language isn't covered
 */
export function phrasesForLanguage(language: string | null): Phrase[] | null {
  if (!language) return null
  return PHRASES_BY_LANGUAGE[language] ?? null
}
