export interface Phrase {
  english: string
  translation: string
}

/**
 * A small set of real, common travel phrases per language — the same kind
 * of static reference data as `currencyByCountry.ts`'s currency codes, not
 * fabricated content. Covers the 8 phrases most useful to a traveler who
 * knows none of the local language. Languages not listed here (or English)
 * fall back to a plain Google Translate link — see `LocalInfoCard`.
 */
export const PHRASES_BY_LANGUAGE: Record<string, Phrase[]> = {
  french: [
    { english: 'Hello', translation: 'Bonjour' },
    { english: 'Please', translation: "S'il vous plaît" },
    { english: 'Thank you', translation: 'Merci' },
    { english: 'Excuse me', translation: 'Excusez-moi' },
    { english: 'Yes / No', translation: 'Oui / Non' },
    { english: 'How much is this?', translation: 'Combien ça coûte ?' },
    { english: 'Where is the bathroom?', translation: 'Où sont les toilettes ?' },
    { english: 'Help!', translation: 'Au secours !' },
  ],
  german: [
    { english: 'Hello', translation: 'Hallo' },
    { english: 'Please', translation: 'Bitte' },
    { english: 'Thank you', translation: 'Danke' },
    { english: 'Excuse me', translation: 'Entschuldigung' },
    { english: 'Yes / No', translation: 'Ja / Nein' },
    { english: 'How much is this?', translation: 'Wie viel kostet das?' },
    { english: 'Where is the bathroom?', translation: 'Wo ist die Toilette?' },
    { english: 'Help!', translation: 'Hilfe!' },
  ],
  spanish: [
    { english: 'Hello', translation: 'Hola' },
    { english: 'Please', translation: 'Por favor' },
    { english: 'Thank you', translation: 'Gracias' },
    { english: 'Excuse me', translation: 'Disculpe' },
    { english: 'Yes / No', translation: 'Sí / No' },
    { english: 'How much is this?', translation: '¿Cuánto cuesta esto?' },
    { english: 'Where is the bathroom?', translation: '¿Dónde está el baño?' },
    { english: 'Help!', translation: '¡Ayuda!' },
  ],
  italian: [
    { english: 'Hello', translation: 'Ciao' },
    { english: 'Please', translation: 'Per favore' },
    { english: 'Thank you', translation: 'Grazie' },
    { english: 'Excuse me', translation: 'Mi scusi' },
    { english: 'Yes / No', translation: 'Sì / No' },
    { english: 'How much is this?', translation: 'Quanto costa?' },
    { english: 'Where is the bathroom?', translation: "Dov'è il bagno?" },
    { english: 'Help!', translation: 'Aiuto!' },
  ],
  portuguese: [
    { english: 'Hello', translation: 'Olá' },
    { english: 'Please', translation: 'Por favor' },
    { english: 'Thank you', translation: 'Obrigado' },
    { english: 'Excuse me', translation: 'Com licença' },
    { english: 'Yes / No', translation: 'Sim / Não' },
    { english: 'How much is this?', translation: 'Quanto custa isto?' },
    { english: 'Where is the bathroom?', translation: 'Onde é o banheiro?' },
    { english: 'Help!', translation: 'Socorro!' },
  ],
  japanese: [
    { english: 'Hello', translation: 'こんにちは (Konnichiwa)' },
    { english: 'Please', translation: 'お願いします (Onegaishimasu)' },
    { english: 'Thank you', translation: 'ありがとう (Arigatou)' },
    { english: 'Excuse me', translation: 'すみません (Sumimasen)' },
    { english: 'Yes / No', translation: 'はい / いいえ (Hai / Iie)' },
    { english: 'How much is this?', translation: 'これはいくらですか？ (Kore wa ikura desu ka?)' },
    { english: 'Where is the bathroom?', translation: 'トイレはどこですか？ (Toire wa doko desu ka?)' },
    { english: 'Help!', translation: '助けて！ (Tasukete!)' },
  ],
  mandarin: [
    { english: 'Hello', translation: '你好 (Nǐ hǎo)' },
    { english: 'Please', translation: '请 (Qǐng)' },
    { english: 'Thank you', translation: '谢谢 (Xièxiè)' },
    { english: 'Excuse me', translation: '对不起 (Duìbùqǐ)' },
    { english: 'Yes / No', translation: '是 / 不是 (Shì / Bùshì)' },
    { english: 'How much is this?', translation: '这个多少钱？ (Zhège duōshǎo qián?)' },
    { english: 'Where is the bathroom?', translation: '厕所在哪里？ (Cèsuǒ zài nǎlǐ?)' },
    { english: 'Help!', translation: '救命！ (Jiùmìng!)' },
  ],
  korean: [
    { english: 'Hello', translation: '안녕하세요 (Annyeonghaseyo)' },
    { english: 'Please', translation: '부탁합니다 (Butakhamnida)' },
    { english: 'Thank you', translation: '감사합니다 (Gamsahamnida)' },
    { english: 'Excuse me', translation: '실례합니다 (Sillyehamnida)' },
    { english: 'Yes / No', translation: '네 / 아니요 (Ne / Aniyo)' },
    { english: 'How much is this?', translation: '이거 얼마예요? (Igeo eolmayeyo?)' },
    { english: 'Where is the bathroom?', translation: '화장실이 어디예요? (Hwajangsiri eodiyeyo?)' },
    { english: 'Help!', translation: '도와주세요! (Dowajuseyo!)' },
  ],
  thai: [
    { english: 'Hello', translation: 'สวัสดี (Sawasdee)' },
    { english: 'Please', translation: 'กรุณา (Karuna)' },
    { english: 'Thank you', translation: 'ขอบคุณ (Khob khun)' },
    { english: 'Excuse me', translation: 'ขอโทษ (Kho thot)' },
    { english: 'Yes / No', translation: 'ใช่ / ไม่ (Chai / Mai)' },
    { english: 'How much is this?', translation: 'นี่ราคาเท่าไหร่? (Nee raka tao rai?)' },
    { english: 'Where is the bathroom?', translation: 'ห้องน้ำอยู่ที่ไหน? (Hong nam yu tee nai?)' },
    { english: 'Help!', translation: 'ช่วยด้วย! (Chuay duay!)' },
  ],
  vietnamese: [
    { english: 'Hello', translation: 'Xin chào' },
    { english: 'Please', translation: 'Làm ơn' },
    { english: 'Thank you', translation: 'Cảm ơn' },
    { english: 'Excuse me', translation: 'Xin lỗi' },
    { english: 'Yes / No', translation: 'Vâng / Không' },
    { english: 'How much is this?', translation: 'Cái này bao nhiêu tiền?' },
    { english: 'Where is the bathroom?', translation: 'Nhà vệ sinh ở đâu?' },
    { english: 'Help!', translation: 'Cứu tôi với!' },
  ],
  indonesian: [
    { english: 'Hello', translation: 'Halo' },
    { english: 'Please', translation: 'Tolong' },
    { english: 'Thank you', translation: 'Terima kasih' },
    { english: 'Excuse me', translation: 'Permisi' },
    { english: 'Yes / No', translation: 'Ya / Tidak' },
    { english: 'How much is this?', translation: 'Berapa harganya?' },
    { english: 'Where is the bathroom?', translation: 'Di mana kamar mandi?' },
    { english: 'Help!', translation: 'Tolong!' },
  ],
  malay: [
    { english: 'Hello', translation: 'Helo' },
    { english: 'Please', translation: 'Tolong' },
    { english: 'Thank you', translation: 'Terima kasih' },
    { english: 'Excuse me', translation: 'Maaf' },
    { english: 'Yes / No', translation: 'Ya / Tidak' },
    { english: 'How much is this?', translation: 'Berapa harganya?' },
    { english: 'Where is the bathroom?', translation: 'Di mana tandas?' },
    { english: 'Help!', translation: 'Tolong!' },
  ],
  dutch: [
    { english: 'Hello', translation: 'Hallo' },
    { english: 'Please', translation: 'Alstublieft' },
    { english: 'Thank you', translation: 'Dank u' },
    { english: 'Excuse me', translation: 'Pardon' },
    { english: 'Yes / No', translation: 'Ja / Nee' },
    { english: 'How much is this?', translation: 'Hoeveel kost dit?' },
    { english: 'Where is the bathroom?', translation: 'Waar is het toilet?' },
    { english: 'Help!', translation: 'Help!' },
  ],
  greek: [
    { english: 'Hello', translation: 'Γεια σας (Geia sas)' },
    { english: 'Please', translation: 'Παρακαλώ (Parakalo)' },
    { english: 'Thank you', translation: 'Ευχαριστώ (Efharisto)' },
    { english: 'Excuse me', translation: 'Συγγνώμη (Signomi)' },
    { english: 'Yes / No', translation: 'Ναι / Όχι (Ne / Ochi)' },
    { english: 'How much is this?', translation: 'Πόσο κοστίζει αυτό; (Poso kostizei afto?)' },
    { english: 'Where is the bathroom?', translation: 'Πού είναι η τουαλέτα; (Pou einai i toualeta?)' },
    { english: 'Help!', translation: 'Βοήθεια! (Voitheia!)' },
  ],
  russian: [
    { english: 'Hello', translation: 'Здравствуйте (Zdravstvuyte)' },
    { english: 'Please', translation: 'Пожалуйста (Pozhaluysta)' },
    { english: 'Thank you', translation: 'Спасибо (Spasibo)' },
    { english: 'Excuse me', translation: 'Извините (Izvinite)' },
    { english: 'Yes / No', translation: 'Да / Нет (Da / Net)' },
    { english: 'How much is this?', translation: 'Сколько это стоит? (Skolko eto stoit?)' },
    { english: 'Where is the bathroom?', translation: 'Где туалет? (Gde tualet?)' },
    { english: 'Help!', translation: 'Помогите! (Pomogite!)' },
  ],
  ukrainian: [
    { english: 'Hello', translation: 'Вітаю (Vitayu)' },
    { english: 'Please', translation: 'Будь ласка (Bud laska)' },
    { english: 'Thank you', translation: 'Дякую (Dyakuyu)' },
    { english: 'Excuse me', translation: 'Вибачте (Vybachte)' },
    { english: 'Yes / No', translation: 'Так / Ні (Tak / Ni)' },
    { english: 'How much is this?', translation: 'Скільки це коштує? (Skilky tse koshtuye?)' },
    { english: 'Where is the bathroom?', translation: 'Де туалет? (De tualet?)' },
    { english: 'Help!', translation: 'Допоможіть! (Dopomozhit!)' },
  ],
  polish: [
    { english: 'Hello', translation: 'Cześć' },
    { english: 'Please', translation: 'Proszę' },
    { english: 'Thank you', translation: 'Dziękuję' },
    { english: 'Excuse me', translation: 'Przepraszam' },
    { english: 'Yes / No', translation: 'Tak / Nie' },
    { english: 'How much is this?', translation: 'Ile to kosztuje?' },
    { english: 'Where is the bathroom?', translation: 'Gdzie jest toaleta?' },
    { english: 'Help!', translation: 'Pomocy!' },
  ],
  turkish: [
    { english: 'Hello', translation: 'Merhaba' },
    { english: 'Please', translation: 'Lütfen' },
    { english: 'Thank you', translation: 'Teşekkürler' },
    { english: 'Excuse me', translation: 'Affedersiniz' },
    { english: 'Yes / No', translation: 'Evet / Hayır' },
    { english: 'How much is this?', translation: 'Bu ne kadar?' },
    { english: 'Where is the bathroom?', translation: 'Tuvalet nerede?' },
    { english: 'Help!', translation: 'İmdat!' },
  ],
  arabic: [
    { english: 'Hello', translation: 'مرحبا (Marhaba)' },
    { english: 'Please', translation: 'من فضلك (Min fadlik)' },
    { english: 'Thank you', translation: 'شكرا (Shukran)' },
    { english: 'Excuse me', translation: 'عفوا (Afwan)' },
    { english: 'Yes / No', translation: 'نعم / لا (Naam / La)' },
    { english: 'How much is this?', translation: 'كم هذا؟ (Kam hatha?)' },
    { english: 'Where is the bathroom?', translation: 'أين الحمام؟ (Ayna al-hammam?)' },
    { english: 'Help!', translation: 'النجدة! (An-najda!)' },
  ],
  hebrew: [
    { english: 'Hello', translation: 'שלום (Shalom)' },
    { english: 'Please', translation: 'בבקשה (Bevakasha)' },
    { english: 'Thank you', translation: 'תודה (Toda)' },
    { english: 'Excuse me', translation: 'סליחה (Slicha)' },
    { english: 'Yes / No', translation: 'כן / לא (Ken / Lo)' },
    { english: 'How much is this?', translation: 'כמה זה עולה? (Kama ze ole?)' },
    { english: 'Where is the bathroom?', translation: 'איפה השירותים? (Eifo ha-sherutim?)' },
    { english: 'Help!', translation: 'הצילו! (Hatzilu!)' },
  ],
  hindi: [
    { english: 'Hello', translation: 'नमस्ते (Namaste)' },
    { english: 'Please', translation: 'कृपया (Kripya)' },
    { english: 'Thank you', translation: 'धन्यवाद (Dhanyavaad)' },
    { english: 'Excuse me', translation: 'माफ़ कीजिए (Maaf kijiye)' },
    { english: 'Yes / No', translation: 'हाँ / नहीं (Haan / Nahin)' },
    { english: 'How much is this?', translation: 'यह कितने का है? (Yeh kitne ka hai?)' },
    { english: 'Where is the bathroom?', translation: 'शौचालय कहाँ है? (Shauchalay kahaan hai?)' },
    { english: 'Help!', translation: 'मदद करो! (Madad karo!)' },
  ],
  sinhala: [
    { english: 'Hello', translation: 'ආයුබෝවන් (Ayubowan)' },
    { english: 'Please', translation: 'කරුණාකර (Karunakara)' },
    { english: 'Thank you', translation: 'ස්තූතියි (Sthuthiyi)' },
    { english: 'Excuse me', translation: 'සමාවෙන්න (Samavenna)' },
    { english: 'Yes / No', translation: 'ඔව් / නෑ (Ow / Nae)' },
    { english: 'How much is this?', translation: 'මේකට කීයද? (Mekata keeyada?)' },
    { english: 'Where is the bathroom?', translation: 'වැසිකිලිය කොහෙද? (Wasikiliya koheda?)' },
    { english: 'Help!', translation: 'උදව්වක්! (Udawwak!)' },
  ],
  nepali: [
    { english: 'Hello', translation: 'नमस्ते (Namaste)' },
    { english: 'Please', translation: 'कृपया (Kripaya)' },
    { english: 'Thank you', translation: 'धन्यवाद (Dhanyabaad)' },
    { english: 'Excuse me', translation: 'माफ गर्नुहोस् (Maaf garnuhos)' },
    { english: 'Yes / No', translation: 'हो / होइन (Ho / Hoina)' },
    { english: 'How much is this?', translation: 'यो कति हो? (Yo kati ho?)' },
    { english: 'Where is the bathroom?', translation: 'शौचालय कहाँ छ? (Shauchalaya kahan chha?)' },
    { english: 'Help!', translation: 'सहयोग गर्नुहोस्! (Sahayog garnuhos!)' },
  ],
  icelandic: [
    { english: 'Hello', translation: 'Halló' },
    { english: 'Please', translation: 'Vinsamlegast' },
    { english: 'Thank you', translation: 'Takk' },
    { english: 'Excuse me', translation: 'Afsakið' },
    { english: 'Yes / No', translation: 'Já / Nei' },
    { english: 'How much is this?', translation: 'Hvað kostar þetta?' },
    { english: 'Where is the bathroom?', translation: 'Hvar er klósettið?' },
    { english: 'Help!', translation: 'Hjálp!' },
  ],
  norwegian: [
    { english: 'Hello', translation: 'Hei' },
    { english: 'Please', translation: 'Vær så snill' },
    { english: 'Thank you', translation: 'Takk' },
    { english: 'Excuse me', translation: 'Unnskyld' },
    { english: 'Yes / No', translation: 'Ja / Nei' },
    { english: 'How much is this?', translation: 'Hvor mye koster dette?' },
    { english: 'Where is the bathroom?', translation: 'Hvor er toalettet?' },
    { english: 'Help!', translation: 'Hjelp!' },
  ],
  swedish: [
    { english: 'Hello', translation: 'Hej' },
    { english: 'Please', translation: 'Snälla' },
    { english: 'Thank you', translation: 'Tack' },
    { english: 'Excuse me', translation: 'Ursäkta' },
    { english: 'Yes / No', translation: 'Ja / Nej' },
    { english: 'How much is this?', translation: 'Vad kostar det här?' },
    { english: 'Where is the bathroom?', translation: 'Var är toaletten?' },
    { english: 'Help!', translation: 'Hjälp!' },
  ],
  danish: [
    { english: 'Hello', translation: 'Hej' },
    { english: 'Please', translation: 'Vær venlig' },
    { english: 'Thank you', translation: 'Tak' },
    { english: 'Excuse me', translation: 'Undskyld' },
    { english: 'Yes / No', translation: 'Ja / Nej' },
    { english: 'How much is this?', translation: 'Hvor meget koster det?' },
    { english: 'Where is the bathroom?', translation: 'Hvor er toilettet?' },
    { english: 'Help!', translation: 'Hjælp!' },
  ],
  finnish: [
    { english: 'Hello', translation: 'Hei' },
    { english: 'Please', translation: 'Ole hyvä' },
    { english: 'Thank you', translation: 'Kiitos' },
    { english: 'Excuse me', translation: 'Anteeksi' },
    { english: 'Yes / No', translation: 'Kyllä / Ei' },
    { english: 'How much is this?', translation: 'Paljonko tämä maksaa?' },
    { english: 'Where is the bathroom?', translation: 'Missä on vessa?' },
    { english: 'Help!', translation: 'Apua!' },
  ],
  czech: [
    { english: 'Hello', translation: 'Ahoj' },
    { english: 'Please', translation: 'Prosím' },
    { english: 'Thank you', translation: 'Děkuji' },
    { english: 'Excuse me', translation: 'Promiňte' },
    { english: 'Yes / No', translation: 'Ano / Ne' },
    { english: 'How much is this?', translation: 'Kolik to stojí?' },
    { english: 'Where is the bathroom?', translation: 'Kde je toaleta?' },
    { english: 'Help!', translation: 'Pomoc!' },
  ],
  hungarian: [
    { english: 'Hello', translation: 'Szia' },
    { english: 'Please', translation: 'Kérem' },
    { english: 'Thank you', translation: 'Köszönöm' },
    { english: 'Excuse me', translation: 'Elnézést' },
    { english: 'Yes / No', translation: 'Igen / Nem' },
    { english: 'How much is this?', translation: 'Mennyibe kerül ez?' },
    { english: 'Where is the bathroom?', translation: 'Hol van a mosdó?' },
    { english: 'Help!', translation: 'Segítség!' },
  ],
  romanian: [
    { english: 'Hello', translation: 'Bună' },
    { english: 'Please', translation: 'Vă rog' },
    { english: 'Thank you', translation: 'Mulțumesc' },
    { english: 'Excuse me', translation: 'Scuzați-mă' },
    { english: 'Yes / No', translation: 'Da / Nu' },
    { english: 'How much is this?', translation: 'Cât costă asta?' },
    { english: 'Where is the bathroom?', translation: 'Unde este toaleta?' },
    { english: 'Help!', translation: 'Ajutor!' },
  ],
  croatian: [
    { english: 'Hello', translation: 'Bok' },
    { english: 'Please', translation: 'Molim' },
    { english: 'Thank you', translation: 'Hvala' },
    { english: 'Excuse me', translation: 'Oprostite' },
    { english: 'Yes / No', translation: 'Da / Ne' },
    { english: 'How much is this?', translation: 'Koliko ovo košta?' },
    { english: 'Where is the bathroom?', translation: 'Gdje je zahod?' },
    { english: 'Help!', translation: 'Upomoć!' },
  ],
}

/**
 * Looks up the real phrase list for a language, if one is curated.
 * @param language - A language key from `languageForDisplayName`, or null
 * @returns The phrase list, or null when the language isn't covered
 */
export function phrasesForLanguage(language: string | null): Phrase[] | null {
  if (!language) return null
  return PHRASES_BY_LANGUAGE[language] ?? null
}
